version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        PYTHON_VARIANT: 3.9
        JAVA_VARIANT: 11-bullseye
    volumes:
      - ..:/workspace:cached
    command: sleep infinity

  pyspark:
    image: jupyter/pyspark-notebook:latest
  # Specify kernel
    environment: 
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=somecomplicatedpassword#fdcs2#4
      - JUPYTER_ALLOW_ORIGIN=*
    ports: 
      - 8889:8888